apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector: # you are telling the deployment to look for a pod that has the key value pair of app=auth
    matchLabels:
      app: auth
  template: # you are telling the deployment to create a pod with specific name (app=auth)
    metadata:
      labels:
        app: auth
    spec:   # config of the pod you are trying to make
      containers:
        - name: auth
          image: us.gcr.io/ticketing-dev-294323/auth
          env:
            - name: JWT_KEY # assign the name of the variable to reference from the deployment (or the source code)
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # name of the secret we created with imperative kubectl command (see README.md)
                  key: JWT_KEY # name of the key in the secret we created with imperative kubectl command (see README.md)
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
      